export const FAWATERAK_DEPOSIT_KIND = {
  BALANCE_TOPUP: "BALANCE_TOPUP",
  COURSE_PURCHASE: "COURSE_PURCHASE",
  SUBSCRIPTION_PURCHASE: "SUBSCRIPTION_PURCHASE",
} as const;

export type FawaterakDepositKind =
  (typeof FAWATERAK_DEPOSIT_KIND)[keyof typeof FAWATERAK_DEPOSIT_KIND];
